/**
 * KVTM 2.0 — Sort Blossom levels DATA (v2 schema)
 * Generated by tools/_gen_levels.js — 30 levels (L1-30)
 * Re-run generator to regenerate variations.
 *
 * Schema:
 *   {
 *     id, name,
 *     pots: [{ active: [L|null, C|null, R|null], queue: [color,...] }, ...],
 *     moveLimit, starThresholds: [3⭐, 2⭐, 1⭐],
 *     tutorial?: boolean,
 *     schemaVersion: 2
 *   }
 */
(function (global) {
  'use strict';

  const SORT_BLOSSOM_LEVELS = [];

  function loadLevels() {
    try {
      const r = localStorage.getItem('kvtm2_levels_v2');
      if (r) {
        const p = JSON.parse(r);
        // Accept if same or more levels than hardcoded (editor push)
        if (Array.isArray(p) && p.length >= SORT_BLOSSOM_LEVELS.length) return p;
        // Accept partial push: merge potLayout overrides into hardcoded levels
        // (editor may have pushed only layout changes, not full level data)
        if (Array.isArray(p) && p.length > 0) {
          const merged = SORT_BLOSSOM_LEVELS.map(lv => {
            const override = p.find(x => x.id === lv.id);
            return override ? Object.assign({}, lv, override) : lv;
          });
          return merged;
        }
      }
    } catch {}
    return SORT_BLOSSOM_LEVELS;
  }

  function saveLevels(levels) {
    try {
      localStorage.setItem('kvtm2_levels_v2', JSON.stringify(levels));
      return true;
    } catch { return false; }
  }

  function defaultLevels() {
    return JSON.parse(JSON.stringify(SORT_BLOSSOM_LEVELS));
  }

  const api = {
    SORT_BLOSSOM_LEVELS,
    loadLevels,
    saveLevels,
    defaultLevels,
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    global.SortBlossomData = api;
  }
})(typeof window !== 'undefined' ? window : globalThis);
