/**
 * KVTM 2.0 — Sort Blossom levels DATA (v2 schema)
 * Generated by tools/_gen_levels.js — 30 levels (L1-30)
 * Re-run generator to regenerate variations.
 *
 * Schema:
 *   {
 *     id, name,
 *     pots: [{ active: [L|null, C|null, R|null], queue: [color,...] }, ...],
 *     moveLimit, starThresholds: [3⭐, 2⭐, 1⭐],
 *     tutorial?: boolean,
 *     schemaVersion: 2
 *   }
 */
(function (global) {
  'use strict';

  const SORT_BLOSSOM_LEVELS = [
  {
    "id": 1,
    "name": "Hoa Hồng Đầu Tiên",
    "pots": [
      {
        "active": [
          "R",
          null,
          null
        ],
        "queue": [
          "R",
          "R"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 8,
    "starThresholds": [
      3,
      5,
      7
    ],
    "tutorial": true,
    "schemaVersion": 2
  },
  {
    "id": 2,
    "name": "Buổi Sáng Êm Ả",
    "pots": [
      {
        "active": [
          "R",
          "P",
          "R"
        ],
        "queue": [
          "P",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "P",
          "R",
          "P"
        ],
        "queue": [
          "R",
          "P",
          "R"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 14,
    "starThresholds": [
      6,
      9,
      13
    ],
    "schemaVersion": 2,
    "potLayout": [
      {
        "x": 87,
        "y": 287
      },
      {
        "x": 314,
        "y": 298
      },
      {
        "x": 199,
        "y": 390
      }
    ]
  },
  {
    "id": 3,
    "name": "Ba Sắc Hoa",
    "pots": [
      {
        "active": [
          "R",
          "P",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "Y",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "P",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 12,
    "starThresholds": [
      4,
      7,
      10
    ],
    "schemaVersion": 2,
    "potLayout": [
      {
        "x": 91,
        "y": 195
      },
      {
        "x": 293,
        "y": 203
      },
      {
        "x": 192,
        "y": 390
      },
      {
        "x": 189,
        "y": 257
      }
    ]
  },
  {
    "id": 4,
    "name": "Vườn Bạch Cúc",
    "pots": [
      {
        "active": [
          "Y",
          "R",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "Y",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 10,
    "starThresholds": [
      6,
      7,
      8
    ],
    "schemaVersion": 2
  },
  {
    "id": 5,
    "name": "Hoa Anh Đào",
    "pots": [
      {
        "active": [
          "R",
          "P",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "P",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 10,
    "starThresholds": [
      6,
      7,
      8
    ],
    "schemaVersion": 2
  },
  {
    "id": 6,
    "name": "Cúc Họa Mi",
    "pots": [
      {
        "active": [
          "Y",
          "P",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "Y",
          "Y",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 10,
    "starThresholds": [
      6,
      7,
      8
    ],
    "schemaVersion": 2
  },
  {
    "id": 7,
    "name": "Tam Sắc Bình Minh",
    "pots": [
      {
        "active": [
          "R",
          "P",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "Y",
          "R",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 8,
    "starThresholds": [
      5,
      7,
      8
    ],
    "schemaVersion": 2,
    "potLayout": [
      {
        "x": 91,
        "y": 219
      },
      {
        "x": 293,
        "y": 220
      },
      {
        "x": 204,
        "y": 398
      },
      {
        "x": 190,
        "y": 254
      }
    ]
  },
  {
    "id": 8,
    "name": "Cánh Đồng Tulip",
    "pots": [
      {
        "active": [
          "R",
          "Y",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 8,
    "starThresholds": [
      5,
      7,
      8
    ],
    "schemaVersion": 2
  },
  {
    "id": 9,
    "name": "Vườn Hoa Sớm",
    "pots": [
      {
        "active": [
          "P",
          "R",
          "P"
        ],
        "queue": [
          "P",
          "P"
        ]
      },
      {
        "active": [
          "Y",
          "Y",
          "P"
        ],
        "queue": [
          "R",
          "R"
        ]
      },
      {
        "active": [
          "R",
          "R",
          "R"
        ],
        "queue": [
          "Y"
        ]
      },
      {
        "active": [
          "Y",
          "P",
          "Y"
        ],
        "queue": [
          "Y"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 18,
    "starThresholds": [
      11,
      14,
      18
    ],
    "schemaVersion": 2,
    "potLayout": [
      {
        "x": 80,
        "y": 146
      },
      {
        "x": 307,
        "y": 144
      },
      {
        "x": 73,
        "y": 349
      },
      {
        "x": 304,
        "y": 368
      },
      {
        "x": 190,
        "y": 243
      }
    ]
  },
  {
    "id": 10,
    "name": "Khu Vườn Bí Mật",
    "pots": [
      {
        "active": [
          "R",
          "Y",
          "Y"
        ],
        "queue": [
          "R",
          "P",
          "R"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "P"
        ],
        "queue": [
          "P",
          "Y",
          "P"
        ]
      },
      {
        "active": [
          "P",
          "Y",
          "R"
        ],
        "queue": [
          "R",
          "P",
          "Y"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 18,
    "starThresholds": [
      11,
      14,
      18
    ],
    "schemaVersion": 2
  },
  {
    "id": 11,
    "name": "Hoa Cẩm Chướng",
    "pots": [
      {
        "active": [
          "R",
          "P",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "Y",
          null
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "R",
          null
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          null
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 10,
    "starThresholds": [
      6,
      8,
      10
    ],
    "schemaVersion": 2
  },
  {
    "id": 12,
    "name": "Vườn Trên Cao",
    "pots": [
      {
        "active": [
          "Y",
          "R",
          "P"
        ],
        "queue": [
          "R",
          "Y"
        ]
      },
      {
        "active": [
          "R",
          "P",
          "R"
        ],
        "queue": [
          "P",
          "Y"
        ]
      },
      {
        "active": [
          "Y",
          "Y",
          "Y"
        ],
        "queue": [
          "P"
        ]
      },
      {
        "active": [
          "P",
          "P",
          "R"
        ],
        "queue": [
          "R"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 18,
    "starThresholds": [
      11,
      14,
      18
    ],
    "schemaVersion": 2
  },
  {
    "id": 13,
    "name": "Bốn Mùa Hoa",
    "pots": [
      {
        "active": [
          "Y",
          "P",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "V",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "P",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "Y",
          "V",
          "V"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 13,
    "starThresholds": [
      8,
      10,
      13
    ],
    "schemaVersion": 2
  },
  {
    "id": 14,
    "name": "Hoa Tử Đinh Hương",
    "pots": [
      {
        "active": [
          "P",
          "V",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "Y",
          "P",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "V",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "R",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 13,
    "starThresholds": [
      8,
      10,
      13
    ],
    "schemaVersion": 2
  },
  {
    "id": 15,
    "name": "Vườn Phượng",
    "pots": [
      {
        "active": [
          "Y",
          "V",
          "P"
        ],
        "queue": [
          "P",
          "R"
        ]
      },
      {
        "active": [
          "V",
          "V",
          "V"
        ],
        "queue": [
          "V",
          "P"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "V"
        ],
        "queue": [
          "P",
          "P"
        ]
      },
      {
        "active": [
          "R",
          "R",
          "Y"
        ],
        "queue": [
          "R",
          "Y"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "P"
        ],
        "queue": [
          "Y"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 24,
    "starThresholds": [
      15,
      19,
      24
    ],
    "schemaVersion": 2
  },
  {
    "id": 16,
    "name": "Hoa Lavender",
    "pots": [
      {
        "active": [
          "P",
          "Y",
          "R"
        ],
        "queue": [
          "Y",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "V",
          "Y",
          "R"
        ],
        "queue": [
          "Y",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "V",
          "P",
          "V"
        ],
        "queue": [
          "R",
          "V",
          "Y"
        ]
      },
      {
        "active": [
          "V",
          "P",
          "Y"
        ],
        "queue": [
          "R",
          "V",
          "P"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 24,
    "starThresholds": [
      15,
      19,
      24
    ],
    "schemaVersion": 2
  },
  {
    "id": 17,
    "name": "Vườn Cẩm Tú Cầu",
    "pots": [
      {
        "active": [
          "Y",
          "R",
          "V"
        ],
        "queue": [
          "V",
          "R"
        ]
      },
      {
        "active": [
          "R",
          "Y",
          "Y"
        ],
        "queue": [
          "V",
          "V"
        ]
      },
      {
        "active": [
          "V",
          "P",
          "Y"
        ],
        "queue": [
          "R",
          "P"
        ]
      },
      {
        "active": [
          "V",
          "R",
          "R"
        ],
        "queue": [
          "P",
          "P"
        ]
      },
      {
        "active": [
          "Y",
          "Y",
          "P"
        ],
        "queue": [
          "P"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 24,
    "starThresholds": [
      15,
      19,
      24
    ],
    "schemaVersion": 2
  },
  {
    "id": 18,
    "name": "Hoa Trắng Tinh Khôi",
    "pots": [
      {
        "active": [
          "P",
          "Y",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "W",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "W",
          "R",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "V",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "W",
          "V",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 15,
    "starThresholds": [
      9,
      12,
      15
    ],
    "schemaVersion": 2
  },
  {
    "id": 19,
    "name": "Vườn Mây",
    "pots": [
      {
        "active": [
          "W",
          "P",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "V",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "Y",
          "W"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "Y",
          "W"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 15,
    "starThresholds": [
      9,
      12,
      15
    ],
    "schemaVersion": 2
  },
  {
    "id": 20,
    "name": "Lá Mùa Thu",
    "pots": [
      {
        "active": [
          "R",
          "R",
          "P"
        ],
        "queue": [
          "P",
          "P"
        ]
      },
      {
        "active": [
          "W",
          "Y",
          "W"
        ],
        "queue": [
          "P",
          "W"
        ]
      },
      {
        "active": [
          "V",
          "W",
          "V"
        ],
        "queue": [
          "P",
          "V"
        ]
      },
      {
        "active": [
          "R",
          "V",
          "R"
        ],
        "queue": [
          "V",
          "R"
        ]
      },
      {
        "active": [
          "Y",
          "W",
          "Y"
        ],
        "queue": [
          "R",
          "W"
        ]
      },
      {
        "active": [
          "P",
          "Y",
          "Y"
        ],
        "queue": [
          "Y",
          "V"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 29,
    "starThresholds": [
      18,
      23,
      29
    ],
    "schemaVersion": 2
  },
  {
    "id": 21,
    "name": "Vườn Bạch Liên",
    "pots": [
      {
        "active": [
          "Y",
          "W",
          "W"
        ],
        "queue": [
          "Y",
          "W",
          "W"
        ]
      },
      {
        "active": [
          "R",
          "V",
          "P"
        ],
        "queue": [
          "P",
          "V",
          "R"
        ]
      },
      {
        "active": [
          "W",
          "P",
          "Y"
        ],
        "queue": [
          "P",
          "R",
          "V"
        ]
      },
      {
        "active": [
          "R",
          "V",
          "V"
        ],
        "queue": [
          "Y",
          "Y",
          "V"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "P"
        ],
        "queue": [
          "W",
          "P",
          "R"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 29,
    "starThresholds": [
      18,
      23,
      29
    ],
    "schemaVersion": 2
  },
  {
    "id": 22,
    "name": "Đỉnh Cao Năm Sắc",
    "pots": [
      {
        "active": [
          "Y",
          "Y",
          "R"
        ],
        "queue": [
          "V",
          "P"
        ]
      },
      {
        "active": [
          "P",
          "P",
          "R"
        ],
        "queue": [
          "Y",
          "W"
        ]
      },
      {
        "active": [
          "P",
          "V",
          "V"
        ],
        "queue": [
          "V",
          "V"
        ]
      },
      {
        "active": [
          "R",
          "P",
          "R"
        ],
        "queue": [
          "R",
          "W"
        ]
      },
      {
        "active": [
          "V",
          "Y",
          "R"
        ],
        "queue": [
          "Y",
          "Y"
        ]
      },
      {
        "active": [
          "P",
          "W",
          "W"
        ],
        "queue": [
          "W",
          "W"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 29,
    "starThresholds": [
      18,
      23,
      29
    ],
    "schemaVersion": 2
  },
  {
    "id": 23,
    "name": "Hoàng Hôn Cam",
    "pots": [
      {
        "active": [
          "R",
          "V",
          "W"
        ],
        "queue": []
      },
      {
        "active": [
          "O",
          "R",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "W",
          "W",
          "O"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "Y"
        ],
        "queue": []
      },
      {
        "active": [
          "R",
          "V",
          "O"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "V"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 18,
    "starThresholds": [
      11,
      14,
      18
    ],
    "schemaVersion": 2
  },
  {
    "id": 24,
    "name": "Vườn Lửa",
    "pots": [
      {
        "active": [
          "R",
          "O",
          "R"
        ],
        "queue": []
      },
      {
        "active": [
          "W",
          "Y",
          "O"
        ],
        "queue": []
      },
      {
        "active": [
          "P",
          "Y",
          "W"
        ],
        "queue": []
      },
      {
        "active": [
          "O",
          "R",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "V",
          "P"
        ],
        "queue": []
      },
      {
        "active": [
          "V",
          "Y",
          "W"
        ],
        "queue": []
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 18,
    "starThresholds": [
      11,
      14,
      18
    ],
    "schemaVersion": 2
  },
  {
    "id": 25,
    "name": "Lễ Hội Sắc Màu",
    "pots": [
      {
        "active": [
          "Y",
          "P",
          "V"
        ],
        "queue": [
          "W",
          "O",
          "V"
        ]
      },
      {
        "active": [
          "O",
          "P",
          "O"
        ],
        "queue": [
          "V",
          "R"
        ]
      },
      {
        "active": [
          "Y",
          "O",
          "R"
        ],
        "queue": [
          "R",
          "V"
        ]
      },
      {
        "active": [
          "R",
          "V",
          "P"
        ],
        "queue": [
          "Y",
          "R"
        ]
      },
      {
        "active": [
          "O",
          "Y",
          "V"
        ],
        "queue": [
          "O",
          "P"
        ]
      },
      {
        "active": [
          "W",
          "W",
          "W"
        ],
        "queue": [
          "W",
          "Y"
        ]
      },
      {
        "active": [
          "P",
          "Y",
          "W"
        ],
        "queue": [
          "P",
          "R"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 36,
    "starThresholds": [
      22,
      28,
      36
    ],
    "schemaVersion": 2
  },
  {
    "id": 26,
    "name": "Vườn Phượng Hoàng",
    "pots": [
      {
        "active": [
          "W",
          "O",
          "V"
        ],
        "queue": [
          "P",
          "V",
          "W"
        ]
      },
      {
        "active": [
          "R",
          "R",
          "W"
        ],
        "queue": [
          "V",
          "W",
          "V"
        ]
      },
      {
        "active": [
          "O",
          "O",
          "O"
        ],
        "queue": [
          "P",
          "Y",
          "P"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "O"
        ],
        "queue": [
          "O",
          "V",
          "W"
        ]
      },
      {
        "active": [
          "W",
          "Y",
          "R"
        ],
        "queue": [
          "Y",
          "P",
          "P"
        ]
      },
      {
        "active": [
          "R",
          "R",
          "P"
        ],
        "queue": [
          "Y",
          "Y",
          "V"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 36,
    "starThresholds": [
      22,
      28,
      36
    ],
    "schemaVersion": 2
  },
  {
    "id": 27,
    "name": "Cầu Vồng Hoa",
    "pots": [
      {
        "active": [
          "V",
          "W",
          "O"
        ],
        "queue": [
          "Y",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "V",
          "R",
          "Y"
        ],
        "queue": [
          "Y",
          "O"
        ]
      },
      {
        "active": [
          "V",
          "P",
          "O"
        ],
        "queue": [
          "P",
          "W"
        ]
      },
      {
        "active": [
          "W",
          "Y",
          "O"
        ],
        "queue": [
          "R",
          "P"
        ]
      },
      {
        "active": [
          "R",
          "Y",
          "P"
        ],
        "queue": [
          "R",
          "V"
        ]
      },
      {
        "active": [
          "O",
          "P",
          "R"
        ],
        "queue": [
          "W",
          "V"
        ]
      },
      {
        "active": [
          "V",
          "W",
          "O"
        ],
        "queue": [
          "Y",
          "W"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 36,
    "starThresholds": [
      22,
      28,
      36
    ],
    "schemaVersion": 2
  },
  {
    "id": 28,
    "name": "Đêm Hội Hoa",
    "pots": [
      {
        "active": [
          "R",
          "V",
          "R"
        ],
        "queue": [
          "P",
          "R",
          "P",
          "V",
          "Y"
        ]
      },
      {
        "active": [
          "O",
          "O",
          "O"
        ],
        "queue": [
          "W",
          "V",
          "R",
          "O",
          "O"
        ]
      },
      {
        "active": [
          "W",
          "Y",
          "P"
        ],
        "queue": [
          "O",
          "Y",
          "Y",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "V",
          "V",
          "W"
        ],
        "queue": [
          "R",
          "Y",
          "R",
          "P",
          "P"
        ]
      },
      {
        "active": [
          "W",
          "O",
          "V"
        ],
        "queue": [
          "Y",
          "W",
          "P",
          "Y",
          "W"
        ]
      },
      {
        "active": [
          "V",
          "Y",
          "V"
        ],
        "queue": [
          "O",
          "V",
          "R",
          "R"
        ]
      },
      {
        "active": [
          "O",
          "W",
          "P"
        ],
        "queue": [
          "P",
          "Y",
          "W",
          "W"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 53,
    "starThresholds": [
      33,
      42,
      53
    ],
    "schemaVersion": 2
  },
  {
    "id": 29,
    "name": "Vũ Điệu Sắc Hoa",
    "pots": [
      {
        "active": [
          "P",
          "P",
          "R"
        ],
        "queue": [
          "R",
          "V",
          "O",
          "O"
        ]
      },
      {
        "active": [
          "V",
          "Y",
          "Y"
        ],
        "queue": [
          "V",
          "W",
          "O",
          "R"
        ]
      },
      {
        "active": [
          "V",
          "W",
          "V"
        ],
        "queue": [
          "Y",
          "W",
          "W",
          "W"
        ]
      },
      {
        "active": [
          "Y",
          "R",
          "P"
        ],
        "queue": [
          "W",
          "P",
          "R",
          "P"
        ]
      },
      {
        "active": [
          "R",
          "P",
          "Y"
        ],
        "queue": [
          "P",
          "O",
          "V",
          "W"
        ]
      },
      {
        "active": [
          "P",
          "O",
          "R"
        ],
        "queue": [
          "V",
          "O",
          "Y",
          "W"
        ]
      },
      {
        "active": [
          "W",
          "O",
          "O"
        ],
        "queue": [
          "Y",
          "R",
          "V"
        ]
      },
      {
        "active": [
          "P",
          "O",
          "Y"
        ],
        "queue": [
          "Y",
          "R",
          "V"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 53,
    "starThresholds": [
      33,
      42,
      53
    ],
    "schemaVersion": 2
  },
  {
    "id": 30,
    "name": "Bậc Thầy Vườn Hoa",
    "pots": [
      {
        "active": [
          "V",
          "O",
          "P"
        ],
        "queue": [
          "W",
          "R",
          "V",
          "P",
          "R",
          "O"
        ]
      },
      {
        "active": [
          "V",
          "V",
          "O"
        ],
        "queue": [
          "R",
          "R",
          "R",
          "P",
          "P",
          "P"
        ]
      },
      {
        "active": [
          "P",
          "R",
          "V"
        ],
        "queue": [
          "P",
          "O",
          "W",
          "V",
          "O",
          "V"
        ]
      },
      {
        "active": [
          "O",
          "Y",
          "P"
        ],
        "queue": [
          "Y",
          "O",
          "Y",
          "O",
          "O",
          "P"
        ]
      },
      {
        "active": [
          "R",
          "R",
          "V"
        ],
        "queue": [
          "Y",
          "W",
          "W",
          "Y",
          "W",
          "W"
        ]
      },
      {
        "active": [
          "Y",
          "V",
          "R"
        ],
        "queue": [
          "V",
          "P",
          "V",
          "O",
          "O",
          "W"
        ]
      },
      {
        "active": [
          "W",
          "Y",
          "Y"
        ],
        "queue": [
          "W",
          "W",
          "P",
          "Y",
          "O",
          "V"
        ]
      },
      {
        "active": [
          "P",
          "R",
          "R"
        ],
        "queue": [
          "R",
          "Y",
          "W",
          "Y",
          "Y",
          "W"
        ]
      },
      {
        "active": [
          null,
          null,
          null
        ],
        "queue": []
      }
    ],
    "moveLimit": 71,
    "starThresholds": [
      44,
      55,
      71
    ],
    "schemaVersion": 2
  }
];

  function loadLevels() {
    try {
      const r = localStorage.getItem('kvtm2_levels_v2');
      if (r) {
        const p = JSON.parse(r);
        // Accept if same or more levels than hardcoded (editor push)
        if (Array.isArray(p) && p.length >= SORT_BLOSSOM_LEVELS.length) return p;
        // Accept partial push: merge potLayout overrides into hardcoded levels
        // (editor may have pushed only layout changes, not full level data)
        if (Array.isArray(p) && p.length > 0) {
          const merged = SORT_BLOSSOM_LEVELS.map(lv => {
            const override = p.find(x => x.id === lv.id);
            return override ? Object.assign({}, lv, override) : lv;
          });
          return merged;
        }
      }
    } catch {}
    return SORT_BLOSSOM_LEVELS;
  }

  function saveLevels(levels) {
    try {
      localStorage.setItem('kvtm2_levels_v2', JSON.stringify(levels));
      return true;
    } catch { return false; }
  }

  function defaultLevels() {
    return JSON.parse(JSON.stringify(SORT_BLOSSOM_LEVELS));
  }

  const api = {
    SORT_BLOSSOM_LEVELS,
    loadLevels,
    saveLevels,
    defaultLevels,
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  } else {
    global.SortBlossomData = api;
  }
})(typeof window !== 'undefined' ? window : globalThis);
